allow-different-user: true

resolver: lts-6.24

packages:
- '.'
- '..'
- '../../gssapi'
extra-deps: []

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []
